service:
  sessionApi:
    enabled: true
    transactions:
      location:
        folder: "docreader-transactions"
        prefix: "session-api"
  database:
    connectionString: "postgresql://postgres:development_password@postgres:5432/reguladb"
  storage:
    type: fs
  processing:
    enabled: true
    results:
      location:
        folder: storage
  webServer:
    port: 8080
    workers: 1
    timeout: 60

    demoApp:
      enabled: true
      webComponent:
        enabled: true

    cors:
      origins: "*"
      headers: "Content-Type"
      methods: "POST,PUT,GET,DELETE,PATCH,HEAD"

    ssl:
      enabled: false
      cert: certs/tls.crt
      key: certs/tls.key
      tlsVersion: 1.2

    logging:
      level: INFO
      formatter: text

      access:
        console: true
        path: logs/docreader-access.log
        format: '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'

      app:
        console: true
        path: logs/docreader-app.log